import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, Menu, X } from 'lucide-react';
import logoPng from '@/assets/logo.png';
import { Button } from '@/components/ui/button';
import { ContactOptions } from './contact-options';
const links = [{to:'/',label:'Home'},{to:'/services',label:'Services'},{to:'/projects',label:'Projects'},{to:'/about',label:'About'},{to:'/contact',label:'Contact'}] as const;
export function Brand() { return <Link to="/" className="brand" aria-label="WebForgeStudio home"><img src={logoPng} alt="WebForgeStudio logo" className="brand-logo" /></Link>; }
export function StartButton({outline=false}:{outline?:boolean}) { return <Button variant={outline?'outline':'studio'} size="lg" asChild><Link to="/start-project">Start a Project <ArrowUpRight /></Link></Button>; }
export function Header() { const [open,setOpen]=useState(false); return <header className="site-header"><div className="container header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{links.map(l=><Link key={l.to} to={l.to} className="nav-link" activeOptions={{exact:true}}>{l.label}</Link>)}</nav><div className="header-cta flex items-center gap-3"><Link to="/login" className="nav-link">Client login</Link><Button variant="studio" asChild><Link to="/start-project">Start a Project <ArrowUpRight/></Link></Button></div><Button className="mobile-toggle" variant="ghost" size="icon" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Mobile navigation">{links.map(l=><Link key={l.to} to={l.to} className="nav-link" onClick={()=>setOpen(false)} activeOptions={{exact:true}}>{l.label}</Link>)}<Link to="/login" className="nav-link" onClick={()=>setOpen(false)}>Client login</Link><Button asChild><Link to="/start-project" onClick={()=>setOpen(false)}>Start a Project <ArrowUpRight/></Link></Button></nav>}</header>; }
export function Footer() { return <footer className="site-footer"><div className="container"><div className="footer-top"><div><Brand/><p>Modern websites for modern businesses.</p><Link to="/login" className="nav-link mt-2 inline-block">Client login</Link></div><nav className="footer-links" aria-label="Footer navigation">{links.map(l=><Link key={l.to} to={l.to} className="nav-link" activeOptions={{exact:true}}>{l.label}</Link>)}</nav></div><div className="footer-bottom"><span>© 2026 WebForgeStudio. All rights reserved.</span><ContactOptions socialOnly/></div></div></footer>; }
